stages:
  - build
  - deploy

build_procedure:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker compose build

deploy_procedure:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$SSH_IP "
        sudo rm -fr /home/ubuntu/cityhallfe/
        git clone https://gitlab.com/pas_smartcitywastemanagement/cityhallfe.git /home/ubuntu/cityhallfe/ &&
        sudo docker stop city-hall-fe &&
        sudo docker rm city-hall-fe &&
        cd /home/ubuntu/cityhallfe/ &&
        sudo docker-compose up -d"
