version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: city-hall-fe
    ports:
      - "80:80"
      - "443:443"
    networks:
      - city-hall-fe-network

networks:
  city-hall-fe-network:
    driver: bridge
